# Generated by Django 4.1.1 on 2022-09-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='current_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
