# Generated by Django 4.1.1 on 2022-09-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_myuser_current_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='current_image',
        ),
    ]
