# Generated by Django 4.1.1 on 2022-10-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_myuser_current_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='old_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
